name: favicon
description: Library for finding favicons in a website, either in a <link> or by predefined URL.
version: 1.0.15
homepage: https://github.com/marcjoha/favicon

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  html: ^0.15.0
  image: ^3.0.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.9
